# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!({ name: "Ian", email: "ian2@test.com", password: "password" })
User.create!({ name: "Larry", email: "Larry@test.com", password: "password" })
User.create!({ name: "Ryan", email: "Ryan@test.com", password: "password" })

Artist.create!({ name: "Bon Iver" })
Artist.create!({ name: "Field Report" })
Artist.create!({ name: "King Gizzard and the Lizard Wizard" })
Artist.create!({ name: "Phil Cook" })
Artist.create!({ name: "Francis and the Lights" })
Artist.create!({ name: "Ghost" })
Artist.create!({ name: "The Sword" })
Artist.create!({ name: "Hiss Golden Messenger" })
Artist.create!({ name: "John Prine" })
Artist.create!({ name: "Metallica" })
Artist.create!({ name: "The Beatles" })
Artist.create!({ name: "Eagles" })
Artist.create!({ name: "AC/DC" })

Album.create!({ name: "22, A Million", artist_id: "1", cover_art_url: "https://images-na.ssl-images-amazon.com/images/I/81J5Mr-uSCL._SL1400_.jpg" })
Album.create!({ name: "Summertime Songs", artist_id: "2", cover_art_url: "https://f4.bcbits.com/img/a0943302486_10.jpg" })
Album.create!({ name: "Infest The Rats' Nest", artist_id: "3", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/2/2e/King_Gizzard_%26_the_Lizard_Wizard_-_Infest_the_Rats%27_Nest.png" })
Album.create!({ name: "i,i", artist_id: "1", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Bon_Iver_-_I%2C_I.png/220px-Bon_Iver_-_I%2C_I.png" })
Album.create!({ name: "As Far as I Can See", artist_id: "4", cover_art_url: "https://cdn.shopify.com/s/files/1/0219/6940/products/PC_As-Far-As-I-Can-See_LP_1_c988f510-e6e4-4c0b-a9ad-7cfb3265e27c_1024x1024.png?v=1556641599" })
Album.create!({ name: "Just For Us", artist_id: "5", cover_art_url: "https://media.pitchfork.com/photos/5a4e9cd2214c074d0337175f/1:1/w_600/Just%20For%20Us%20Francis%20and%20the%20Lights.jpg" })
Album.create!({ name: "Meliora", artist_id: "6", cover_art_url: "https://target.scene7.com/is/image/Target/GUEST_d35d0a83-54fd-4060-8621-b0e1e1df09af?wid=488&hei=488&fmt=pjpeg" })
Album.create!({ name: "High Country", artist_id: "7", cover_art_url: "https://images-na.ssl-images-amazon.com/images/I/41p9WHQNVdL.jpg" })
Album.create!({ name: "Quietly Blowing It", artist_id: "8", cover_art_url: "https://media.pitchfork.com/photos/60da03a2fc3a50e51e1b4450/1:1/w_600/Hiss%20Golden%20Messenger-%20Quietly%20Blowing%20It.jpg" })
Album.create!({ name: "John Prine Live", artist_id: "9", cover_art_url: "https://images-na.ssl-images-amazon.com/images/I/81WyCGeTnrL._SY355_.jpg" })
Album.create!({ name: "Metallica", artist_id: "10", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/2/2c/Metallica_-_Metallica_cover.jpg" })
Album.create!({ name: "Abbey Road", artist_id: "11", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg" })
Album.create!({ name: "Bon Iver, Bon Iver", artist_id: "1", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/5/5f/Bon_iver.jpg" })
Album.create!({ name: "Ride The Lightning", artist_id: "10", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/f/f4/Ridetl.png" })
Album.create!({ name: "Magical Mystery Tour", artist_id: "11", cover_art_url: "https://images-na.ssl-images-amazon.com/images/I/91LrXdPTwZL._SL1500_.jpg" })
Album.create!({ name: "Eagles", artist_id: "12", cover_art_url: "https://images-na.ssl-images-amazon.com/images/I/91bfmDSAmvL._SY355_.jpg" })
Album.create!({ name: "Hotel California", artist_id: "12", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/4/49/Hotelcalifornia.jpg" })
Album.create!({ name: "Let There Be Rock", artist_id: "13", cover_art_url: "https://img.discogs.com/ATjpStR0nd4jXhfuSmeXV-Gk5VI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-961547-1341927600-8014.jpeg.jpg" })
Album.create!({ name: "Highway To Hell", artist_id: "13", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/a/ac/Acdc_Highway_to_Hell.JPG" })
Album.create!({ name: "Ballbreaker", artist_id: "13", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/5/52/Ballbreaker.jpg" })
Album.create!({ name: "Kill Em' All", artist_id: "10", cover_art_url: "https://upload.wikimedia.org/wikipedia/en/5/5c/Metallica_-_Kill_%27Em_All_cover.jpg" })

TopTen.create!({ album_id: 1, user_id: 1 })
TopTen.create!({ album_id: 2, user_id: 1 })
TopTen.create!({ album_id: 3, user_id: 1 })
TopTen.create!({ album_id: 4, user_id: 1 })
TopTen.create!({ album_id: 5, user_id: 1 })
TopTen.create!({ album_id: 6, user_id: 1 })
TopTen.create!({ album_id: 7, user_id: 1 })
TopTen.create!({ album_id: 8, user_id: 1 })
TopTen.create!({ album_id: 9, user_id: 1 })
TopTen.create!({ album_id: 10, user_id: 1 })
